baseurl: /docs
url: https://studentrobotics.org

title: Student Robotics
description: >
  Student Robotics is an exciting annual competition challenging people aged
  16-18 to assemble a team and build fully autonomous robots.

markdown: kramdown
collections:
  - events

plugins:
  - jekyll-redirect-from

links:
  compete: //docs.google.com/forms/d/1Ryg2cfAxfwMOBnT01aj-fzsp51F3B182S5e53ye8aMw/viewform
  volunteer: //docs.google.com/forms/d/1MIGf3P30dw0QAtP8OkxK2v7VRDEAN_54JoZHCVMbqDY/viewform
  donate: //link.justgiving.com/v1/charity/donate/charityId/3118662?tipScheme=TipJar2.1&isRecurring=true&amount=20.00&reference=givingcheckout_tj21

navigation:
  - about
  - compete
  - volunteer

emails:
  teams: teams@studentrobotics.org
  info: info@studentrobotics.org
  kit-support: teams@studentrobotics.org
  accounts: accounts@studentrobotics.org

social:
  - title: GitHub
    icon: github
    link: https://github.com/srobo
  - title: Twitter
    icon: twitter
    link: https://twitter.com/studentrobotics
  - title: YouTube
    icon: youtube-play
    link: https://youtube.com/user/StudentRobotics
  - title: Instagram
    icon: instagram
    link: https://www.instagram.com/student_robotics/
  - title: Facebook
    icon: facebook-official
    link: https://facebook.com/StudentRobotics
  - title: LinkedIn
    icon: linkedin
    link: https://www.linkedin.com/company/10969472/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - gems/
  - Dockerfile
  - _env/
  - _docs/
  - vendor/
