name: Validate

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      BUNDLE_PATH: gems
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
        cache-version: 1

    - name: Build & Validate
      run: rake validate

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build container
      run: docker-compose build

    - name: Build site in container
      run: docker-compose run docs rake build
